version: '3.5'

services:

  redis:
    image: redis
    command: "redis-server --save \"\" --appendonly no"
    ports:
      - "6379:6379"
    networks:
      - compose-services-network


  gateway-internal:
    image: "gcr.io/${GOOGLE_PROJECT_ID}/gateway-internal:latest"
    depends_on:
      - redis
    command:
      - dotnet
      - "GatewayInternal.dll"
      - --redis_connection_string
      - "redis:6379"
    networks:
      - compose-services-network

  gateway:
    image: "gcr.io/${GOOGLE_PROJECT_ID}/gateway:latest"
    depends_on:
      - redis
    environment:
      SPATIAL_REFRESH_TOKEN: "${SPATIAL_REFRESH_TOKEN}"
    command:
      - dotnet
      - "Gateway.dll"
      - --grpc_service_port
      - "4040"
      - --redis_connection_string
      - "redis:6379"
    networks:
      - compose-services-network

  gateway-esp:
    image: "gcr.io/endpoints-release/endpoints-runtime:1.38.0"
    ports:
      - "4040:4040"
      - "8080:8080"
    volumes:
      - "${GOOGLE_SECRET_KEY_JSON_SERVICES_ENDPOINT}:/secrets/json/services-endpoint.json"
    command:
      - "--service=gateway.endpoints.${GOOGLE_PROJECT_ID}.cloud.goog"
      - "--rollout_strategy=managed"
      - "--http_port=8080"
      - "--http2_port=4040"
      - "--backend=grpc://gateway:4040"
      - "--service_account_key=/secrets/json/services-endpoint.json"
    networks:
      - compose-services-network

  party:
    image: "gcr.io/${GOOGLE_PROJECT_ID}/party:latest"
    depends_on:
      - redis
    environment:
      SPATIAL_REFRESH_TOKEN: "${SPATIAL_REFRESH_TOKEN}"
    command:
      - dotnet
      - "Party.dll"
      - --grpc_service_port
      - "4040"
      - --redis_connection_string
      - "redis:6379"
    networks:
      - compose-services-network

  party-esp:
    image: "gcr.io/endpoints-release/endpoints-runtime:1.38.0"
    ports:
      - "4041:4040"
      - "8081:8080"
    volumes:
      - "${GOOGLE_SECRET_KEY_JSON_SERVICES_ENDPOINT}:/secrets/json/services-endpoint.json"
    command:
      - "--service=party.endpoints.${GOOGLE_PROJECT_ID}.cloud.goog"
      - "--rollout_strategy=managed"
      - "--http_port=8080"
      - "--http2_port=4040"
      - "--backend=grpc://party:4040"
      - "--service_account_key=/secrets/json/services-endpoint.json"
    networks:
      - compose-services-network

  playfab-auth:
    image: "gcr.io/${GOOGLE_PROJECT_ID}/playfab-auth:latest"
    environment:
      PLAYFAB_SECRET_KEY: "${PLAYFAB_SECRET_KEY}"
      SPATIAL_REFRESH_TOKEN: "${SPATIAL_REFRESH_TOKEN}"
    command:
      - dotnet
      - "PlayfabAuth.dll"
      - --grpc_service_port
      - "4040"
      - --playfab_title_id
      - "${PLAYFAB_TITLE_ID}"
      - --spatial_project
      - "${SPATIAL_PROJECT}"
    networks:
      - compose-services-network

  playfab-auth-esp:
    image: "gcr.io/endpoints-release/endpoints-runtime:1.38.0"
    ports:
      - "4042:4040"
      - "8082:8080"
    volumes:
      - "${GOOGLE_SECRET_KEY_JSON_SERVICES_ENDPOINT}:/secrets/json/services-endpoint.json"
    command:
      - "--service=playfab-auth.endpoints.${GOOGLE_PROJECT_ID}.cloud.goog"
      - "--rollout_strategy=managed"
      - "--http_port=8080"
      - "--http2_port=4040"
      - "--backend=grpc://playfab-auth:4040"
      - "--service_account_key=/secrets/json/services-endpoint.json"
    networks:
      - compose-services-network

  matcher:
    image: "gcr.io/${GOOGLE_PROJECT_ID}/sample-matcher:latest"
    environment:
      SPATIAL_REFRESH_TOKEN: "${SPATIAL_REFRESH_TOKEN}"
      SPATIAL_PROJECT: "${SPATIAL_PROJECT}"
      GATEWAY_SERVICE_TARGET: "gateway-internal:4040"
    networks:
      - compose-services-network

networks:
  compose-services-network:
    name: compose-services-network
