apiVersion: v1
kind: ConfigMap
metadata:
  name: online-services-config
  selfLink: /api/v1/namespaces/default/configmaps/online-services-config
data:
  redis.connection-string: "[your Redis host]:6379"
  spatialos.project: "[your spatialOS project]"