apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-internal
  labels:
    app: gateway-internal
spec:
  replicas: 1
  selector:
      matchLabels:
        app: gateway-internal
  template:
    metadata:
      labels:
        app: gateway-internal
    spec:
      containers:
      - name: gateway-internal
        image: gcr.io/{{your_google_project_id}}/gateway-internal
        imagePullPolicy: Always
        ports:
        - containerPort: 4040
          protocol: TCP
        - containerPort: 8080
          name: 'metrics'
          protocol: TCP
        env:
        - name: SPATIAL_REFRESH_TOKEN
          valueFrom:
            secretKeyRef:
              name: spatialos-refresh-token
              key: service-account.txt
        - name: REDIS_CONNECTION_STRING
          valueFrom:
            configMapKeyRef:
              name: online-services-config
              key: redis.connection-string
        - name: SPATIAL_PROJECT
          valueFrom:
            configMapKeyRef:
              name: online-services-config
              key: spatialos.project
        args:
        # Gateway Internal Arguments
        - --redis_connection_string
        - "$(REDIS_CONNECTION_STRING)"
        - --grpc_service_port
        - "4040"
        # Analytics Instrumentation Arguments
        - --analytics.endpoint
        - "http://analytics.endpoints.[your Google project id].cloud.goog:80/v1/event"
        - --analytics.allow-insecure-endpoint
        - --analytics.config-file-path
        - "/config/analytics-config.yaml"
        - --analytics.gcp-key-path
        - "/secrets/analytics-api-key.txt"
        - --analytics.environment
        - "[your analytics environment]" # Update: {testing, staging, ...}
        volumeMounts:
        - mountPath: /secrets/
          name: analytics-api-key
        - mountPath: /config/
          name: analytics-config
      volumes:
      - name: analytics-api-key
        secret:
          secretName: analytics-api-key
      - name: analytics-config
        configMap:
          name: analytics-config
